runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/headless-angular-project/index.html
  upload: dist/headless-angular-project/index.html

- url: /
  static_dir: dist/headless-angular-project